### ISSUE TITLE
ImportError: cannot import name 'WindroseAxes'

### ISSUE THREAD

**Issue by joddm** [scls19fr/windrose#30]
I use Python 3.5, i have used `pip3 install windrose`, but when I try to run my script I get a error message:

```
dhcp712-stud2:~ JDMac$ python3 windrose.py
Traceback (most recent call last):
  File "windrose.py", line 8, in <module>
    from windrose import WindroseAxes
  File "/Users/JDMac/windrose.py", line 8, in <module>
    from windrose import WindroseAxes
ImportError: cannot import name 'WindroseAxes'

```
My code `windrose.py` that I try to run: 

```
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import matplotlib.cm as cm
import numpy as np
from math import pi

from windrose import WindroseAxes

df = pd.read_csv("WIND10M_7081N_1975E.txt", names=['YEAR','M','D','H','WSP','WDIR'], header=None, delim_whitespace=True)

ax = windrose.WindroseAxes.from_ax()
ax.bar(df.WDIR, df.WSP, normed=True, opening=0.8, edgecolor='white')
ax.set_legend()
```

I have installed all dependencies:

```
dhcp712-stud2:~ JDMac$ pip3 install windrose
Requirement already satisfied (use --upgrade to upgrade): windrose in /usr/local/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python3.5/site-packages (from windrose)
Requirement already satisfied (use --upgrade to upgrade): matplotlib in /usr/local/lib/python3.5/site-packages (from windrose)
Requirement already satisfied (use --upgrade to upgrade): cycler in /usr/local/lib/python3.5/site-packages (from matplotlib->windrose)
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/local/lib/python3.5/site-packages (from matplotlib->windrose)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/lib/python3.5/site-packages (from matplotlib->windrose)
Requirement already satisfied (use --upgrade to upgrade): pyparsing!=2.0.0,!=2.0.4,>=1.5.6 in /usr/local/lib/python3.5/site-packages (from matplotlib->windrose)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python3.5/site-packages (from cycler->matplotlib->windrose)
```

**Comment by scls19fr** [comment]
You should name your script differently because there is a conflict between your script name and this library name (windrose)
try to rename `windrose.py` to `myscript.py`

**Comment by joddm** [comment]
Thanks for the response. I already tried that, unfortunately it doesn't work.

```
Johans-MBP:~ JDMac$ python3 myscript.py
Traceback (most recent call last):
  File "myscript.py", line 1, in <module>
    from windrose import WindroseAxes
  File "/Users/JDMac/windrose.py", line 1, in <module>
    from windrose import WindroseAxes
ImportError: cannot import name 'WindroseAxes'
```

**Comment by scls19fr** [comment]
Did you also rename `windrose.pyc` ?

**Comment by scls19fr** [comment]
Did you also delete windrose.pyc ?

**Comment by joddm** [comment]
Now it works, I had to delete the original. Thanks!

**Comment by scls19fr** [comment]
Ok so closing.
Glad to help
